# ==========================================
# STAGE 1: PABRIK (BUILDER)
# ==========================================
FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# ==========================================
# STAGE 2: ETALASE (PRODUCTION RUNNER)
# ==========================================
FROM node:22-alpine
WORKDIR /app

COPY --from=build /app/.output/ ./

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

# <-- Diperbaiki: Tambah titik (.) agar mengeksekusi di dalam WORKDIR /app
CMD ["node", "./server/index.mjs"]